# Generated by Django 2.2.6 on 2021-01-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('otp', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('email2', models.EmailField(blank=True, max_length=255, null=True)),
                ('email3', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField()),
                ('is_block', models.BooleanField(default=False)),
                ('time_track', models.FloatField(default=0.0)),
            ],
        ),
    ]
